name: Build and publish docker image

on:
  push:
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.SECRET_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ghcr.io/taumaaa/ue19-lab-05:latest .

    - name: Push the Docker image
      run: docker push ghcr.io/taumaaa/ue19-lab-05:latest
      
