name: Build and publish docker image

on:
  push:
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET }}

    - name: Build the Docker image
      run: docker build -t github.com/taumaaa/ue19-lab-05:latest .

    - name: Push the Docker image
      run: docker push github.com/taumaaa/ue19-lab-05:latest
